// const url = "https://api.dicebear.com/9.x/"
const url = "/avatars/"

const AVATAR_NAMES_BY_PREFIX = {
  adventurer: [
    "Amaya",
    "Andrea",
    "Avery",
    "Brian",
    "Caleb",
    "Destiny",
    "Eliza",
    "George",
    "Jack",
    "Jude",
    "Katherine",
    "Kingston",
    "Luis",
    "Mackenzie",
    "Nolan",
    "Robert",
    "Ryan",
    "Ryker",
    "Sophia",
    "Valentina",
  ],
  "adventurer-neutral": [
    "Adrian",
    "Aidan",
    "Aiden",
    "Alexander",
    "Amaya",
    "Brooklynn",
    "Caleb",
    "Chase",
    "Christian",
    "Christopher",
    "Destiny",
    "Eliza",
    "Jade",
    "Jessica",
    "Kingston",
    "Leo",
    "Oliver",
    "Ryker",
    "Valentina",
    "Vivian",
  ],
  notionists: [
    "Amaya",
    "Andrea",
    "Avery",
    "Brian",
    "Caleb",
    "Destiny",
    "Eliza",
    "George",
    "Jack",
    "Jude",
    "Katherine",
    "Kingston",
    "Luis",
    "Mackenzie",
    "Nolan",
    "Robert",
    "Ryan",
    "Ryker",
    "Sophia",
    "Valentina",
  ],
  "notionists-neutral": [
    "Amaya",
    "Andrea",
    "Avery",
    "Brian",
    "Caleb",
    "Destiny",
    "Eliza",
    "George",
    "Jack",
    "Jude",
    "Katherine",
    "Kingston",
    "Luis",
    "Mackenzie",
    "Nolan",
    "Robert",
    "Ryan",
    "Ryker",
    "Sophia",
    "Valentina",
  ],
  "big-smile": ["Alexander", "Andrea", "Eden", "Jude", "Kingston", "Mason", "Ryan"],
  lorelei: ["Andrea", "Brian", "Brooklynn", "Eden", "Eliza", "Emery", "Liam", "Mackenzie", "Riley"],
  bottts: ["Amaya", "Christopher", "Destiny", "Jessica", "Ryker"],
  thumbs: ["Aidan", "Alexander", "Chase", "Leo", "Oliver", "Ryker"],
} as const

export const USER_AVATAR_OPTIONS = (() => {
  const out: string[] = []
  for (const [prefix, names] of Object.entries(AVATAR_NAMES_BY_PREFIX)) {
    for (const name of names) out.push(`${url}${prefix}/${name}.webp`)
  }
  return out
})()
